apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
     app: miappmovil
     tipo: movil
     ambiente: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80