apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
     app: myapp
     tipo: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
