apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
     app: movilapp
     tipo: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: movilapp
    spec:
      containers:
        - name: myapp-container
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: movilapp
